# Flappy Bird Junco Sim
2D flight sim for EECE5500 Mobile Robotics

In [2]:
############################### Import libraries ###############################
import os
import glob
import time
from datetime import datetime

from PIL import Image

import matplotlib.pyplot as plt
%matplotlib qt

import numpy as np
from numpy import matlib
import scipy as sci

import gym
import control as ctrl
import ConvexMotionPlanning
from rrtplanner import RRTStar

In [78]:
class Drone():
    dt = 0.01
    m = 3.2
    Iyy = 1/12*m*0.8**2

    S = 0.25
    c = 0.13

    Cl_0 = 0.5
    Cl_alpha = 0.1*180/np.pi

    Cd_0 = 0.1
    K = 0.05

    Cm_0 = 0.5
    Cm_alpha = -0.14*180/np.pi
    Cm_alpha_dot = -0.008*180/np.pi
    Cm_delta_e = 0.2

    g = 9.81

    vNom = 20
    rhoNom = 1.225
    qNom = 0.5*rhoNom*vNom**2

    Qestimation = np.diag([1/100, 0.1/180*np.pi**2, 0.1/180*np.pi**2,0.1/180*np.pi**2 ])
    Pestimation = np.eye(4)/100
    Restimation = np.diag([0.25, (0.25/180*np.pi)**2])
    stateEstimate = np.array([0.0,0.0,0.0,0.0])

    lidar_range = 50
    lidar_angle = 100*np.pi/180
    lidar_res = int(lidar_angle*180/np.pi)
    lidar = [lidar_range, lidar_angle, lidar_res]
    
    def __init__(self):
        self.x_thres = 10000
        self.z_thresHigh = 500
        self.z_thresLow = 0
        self.v_thres = 50
        self.theta_thres = np.pi/6
        self.theta_dot_thres = np.pi
        self.gamma_thres = np.pi/6
        self.grid = []
        # ???
        self.delta_e_stale = 0
        self.thrust_stale = 0


        self.limits = np.array([
            self.x_thres,
            self.z_thresHigh,
            self.z_thresLow,
            self.v_thres,
            self.theta_thres,
            self.theta_dot_thres,
            self.gamma_thres
        ])

        self.state = None
        self.prev_action = None
        self.steps_beyond_terminated = None
        self.time = 0.

        self.objects = None

    def thetaFromElevator(self, T,thetaDes, delta_e):
        alphaNom = -(self.Cm_0+self.Cm_delta_e*delta_e)/self.Cm_alpha
        Clnom = self.Cl_0 + self.Cl_alpha*alphaNom
        Cdnom = self.Cd_0 + self.K*Clnom**2
        return thetaDes- (-Cdnom/Clnom + T/(self.m*self.g)*(1-Cdnom/Clnom*alphaNom))-alphaNom

    def vGammaFromElevator(self, T, delta_e):
        alphaNom = -(self.Cm_0+self.Cm_delta_e*delta_e)/self.Cm_alpha
        Clnom = self.Cl_0 + self.Cl_alpha*alphaNom
        Cdnom = self.Cd_0 + self.K*Clnom**2
        gammaNom = Cdnom/Clnom*(1-T/self.m/self.g*np.sin(alphaNom)) + T*np.cos(alphaNom)/self.m/self.g
        vNom = np.sqrt(2*(-T*np.sin(alphaNom)+self.m*self.g*np.cos(gammaNom))/(self.S*self.rhoNom))
        return vNom, gammaNom

    def solveForElevator(self, T, thetaDes):
        func = lambda x: self.thetaFromElivator(T, thetaDes,x)
        sol = sci.optimize.root_scalar(func, method='secant', x0 = 0, x1 = 1)
        return sol.root
    
    def elevatorFromAlpha(self, alpha):
        return -(self.Cm_alpha*alpha+self.Cm_0)/self.Cm_delta_e 

    # Calculates a "coherent" (steady state stable) command from thrust and gamma command
    # Returns airspeed, theta, thetadot, and flight path angle (gamma)
    def coherentCommand(self, T, gamma):
        airspeed = self.vNom
        theta = 0
        thetaDot = 0
        verticalForces = lambda X: ((self.Cl_0 + self.Cl_alpha*(X[0]- gamma))*1/2*(X[1]**2)*self.rhoNom*self.S - self.m*self.g*np.cos(gamma) + T*np.sin(X[0]-gamma), \
               ((self.Cd_0+self.K*(self.Cl_0 + self.Cl_alpha*(X[0]- gamma))**2)*1/2*(X[1]**2)*self.rhoNom*self.S -T*np.cos(X[0]-gamma)-self.m*self.g*np.sin(gamma)))

        sol = sci.optimize.root(verticalForces, x0 = [theta, airspeed])
        X =sol.x      
        return [sol.x[1], sol.x[0], thetaDot, gamma]

    # Returns a continous time Jacobian for state and control
    def calculateCTSABMatrix(self, stateIn, controlIn):
        (thrust, delta_e) = controlIn
        v, theta, theta_dot, gamma = stateIn
        q = 0.5*self.rhoNom*v**2
        alpha = theta-gamma

        #Calculate alphaDot
        Cl = self.Cl_0 + self.Cl_alpha*alpha
        L = q*self.S*Cl
        gamma_dot = (L - self.m*self.g*np.cos(gamma) +thrust*np.sin(alpha)) / (self.m*v)
        alpha_dot = theta_dot-gamma_dot

        #Other aero
        Cd = self.Cd_0 + self.K*Cl**2
        Cm = self.Cm_0 + self.Cm_alpha*alpha + self.Cm_alpha_dot*alpha_dot + self.Cm_delta_e*delta_e
        D = q*self.S*Cd
        M = q*self.S*Cm

        #Partial derivatives of aeroforces
        pDpv = self.rhoNom*v*self.S*Cd
        pDptheta = 2*self.K*q*self.S*(self.Cl_alpha * self.Cl_0 + self.Cl_alpha**2*alpha)
        pDpthetaDot = 0
        pDpgamma = -2*self.K*q*self.S*(self.Cl_alpha* self.Cl_0+self.Cl_alpha**2*alpha)
        pMpv = self.rhoNom*v*self.S*Cm
        pMptheta = q*self.S*self.Cm_alpha
        pMpthetaDot = 0
        pMpgamma = -q*self.S*self.Cm_alpha
        pLpv = self.rhoNom*v*self.S*Cl
        pLptheta = q*self.Cl_alpha*self.S
        pLpthetaDot = 0
        pLpgamma = -q*self.Cl_alpha*self.S

        #out of order entries
        pf4ptheta = (pLptheta + thrust*np.cos(alpha))/(self.m*v)
        pf4pgamma = (pLpgamma/self.m +self.g*np.sin(gamma)-thrust/self.m*np.cos(alpha))/v

        #Partial derivatives of nonlinear map with respect to tstate
        pf1pv = - 1/self.m*pDpv
        pf1ptheta = (-pDptheta-thrust*np.sin(alpha))/self.m
        pf1pthetaDot = 0
        pf1pgamma = (-pDpgamma/self.m - self.g*np.cos(gamma) + thrust/self.m*np.sin(alpha))
        pf2pv = 0
        pf2ptheta = 0
        pf2pthetaDot = 1
        pf2pgamma = 0
        pf3pv = pMpv/self.Iyy
        pf3ptheta = pMptheta/self.Iyy
        pf3pthetaDot = 0
        pf3pgamma = pMpgamma/self.Iyy
        pf4pv = pLpv/(self.m*v)
        pf4pthetaDot = 0

        AFull = np.array([[pf1pv, pf1ptheta, pf1pthetaDot, pf1pgamma],[pf2pv, pf2ptheta, pf2pthetaDot, pf2pgamma],
                      [pf3pv, pf3ptheta, pf3pthetaDot, pf3pgamma],[pf4pv, pf4ptheta, pf4pthetaDot, pf4pgamma]])
        BFull = np.array([[0], [0], [q*self.Cm_delta_e*self.S],[0]])
        return AFull, BFull

    def calculateGains(self):
        x, y, v, theta, theta_dot, gamma = self.state
        AFull, BFull =  self.calculateCTSABMatrix(self.state[2:], (4, self.elevatorFromAlpha(self.state[3] - self.state[5])))
        Qcontrol =  np.array([[10,0,0,0],[0,10, 0,0], [0,0, 0,0], [0, 0, 0, 10000]])
        Rcontrol =  np.array([[1]])
        Ncontrol = np.zeros([4, 1])
        H = np.array([[1,0,0,0],[0,1,0,0]])

        self.KFull = ctrl.lqr(AFull, BFull, Qcontrol, Rcontrol)[0]

    def EKF(self, controlIn):
        v, theta, theta_dot, gamma = self.stateEstimate
        alpha = theta-gamma
        q = 0.5*self.rhoNom*v**2

        #Calculate alphaDot
        Cl = self.Cl_0 + self.Cl_alpha*alpha
        L = q*self.S*Cl
        gamma_dot = (L - self.m*self.g*np.cos(gamma) +self.thrust_stale*np.sin(alpha)) / (self.m*v)
        alpha_dot = theta_dot-gamma_dot

        #Other aero
        Cd = self.Cd_0 + self.K*Cl**2
        Cm = self.Cm_0 + self.Cm_alpha*alpha + self.Cm_alpha_dot*alpha_dot + self.Cm_delta_e*self.delta_e_stale
        D = q*self.S*Cd
        M = q*self.S*Cm

        #derivatives
        v_dot = (-D - self.m*self.g*np.sin(gamma) + self.thrust_stale*np.cos(alpha)) / self.m
        #theta_dot = theta_dot
        theta_ddot = M / self.Iyy
        gamma_dot = (L - self.m*self.g*np.cos(gamma) +self.thrust_stale*np.sin(alpha)) / (self.m*v)

        AFull, BFull = self.calculateCTSABMatrix([v, theta, theta_dot, gamma], controlIn)
        F = AFull*self.dt + np.eye(4) 

        #Observability 
        h = np.array([[self.state[2]],[self.state[3]]])
        H = np.array([[1.0,0.0,0.0,0.0],[0.0,1.0,0.0,0.0]])

        #predict
        v += v_dot*self.dt
        theta += theta_dot*self.dt 
        theta_dot += theta_ddot * self.dt
        gamma += gamma_dot*self.dt
        xEst = np.array([[v], [theta], [theta_dot], [gamma]])

        self.Pestimation = (F)@self.Pestimation @ np.transpose(F) + self.Qestimation
        #update
        y = np.array([[v],[theta]]) - np.array([[self.state[2]],[self.state[3]]]) + np.array([np.random.multivariate_normal([0,0], self.Restimation)]).T
        S = H @ self.Pestimation @ H.T + self.Restimation
        K = self.Pestimation @ np.transpose(H) @ sci.linalg.inv(S)
        xEst -= K @ y
        self.Pestimation = (np.eye(4) - K @ H) @ self.Pestimation
        self.stateEstimate = xEst.flatten()

    def calculateStateDerivatives(self, state, control, rho):
        x, z, v, theta, theta_dot, gamma = state
        q = 0.5*rho*v**2
        alpha = theta - gamma
        (thrust, delta_e) = control

        #alpha dot
        Cl = self.Cl_0 + self.Cl_alpha*alpha
        L = q*self.S*Cl
        gamma_dot = (L - self.m*self.g*np.cos(gamma) +thrust*np.sin(alpha)) / (self.m*v)
        alpha_dot = theta_dot-gamma_dot

        # Forces
        Cd = self.Cd_0 + self.K*Cl**2
        Cm = self.Cm_0 + self.Cm_alpha*alpha + self.Cm_alpha_dot*alpha_dot + self.Cm_delta_e*delta_e
        D = q*self.S*Cd
        M = q*self.S*Cm

        #derivatives
        x_dot = v*np.cos(gamma)
        z_dot = v*np.sin(gamma)
        v_dot = (-D - self.m*self.g*np.sin(gamma) + thrust*np.cos(alpha)) / self.m
        theta_dot = theta_dot
        theta_ddot = M / self.Iyy
        return np.array([[x_dot], [z_dot], [v_dot], [theta_dot], [theta_ddot], [gamma_dot]])
    
    def calculateANumerical(self, state, control, rho, step):
        base = self.calculateStateDerivatives(state, control, rho)
        A = []
        for i in range(6):
            delta = np.zeros_like(state)
            delta[i] = step
            deltaF = self.calculateStateDerivatives(state+delta, control, rho)
            if (i >= 1):
                A = np.hstack((A, (deltaF-base)/step))
            else:
                A = (deltaF-base)/step
        return A
    
    def update_plot(self, ax,state,lidar,objects,beams=False):

        # filter objects to ones in lidar cone
        def seenObjects(state,angle,beam,objects):

            x,y,theta = state

            # objects within range
            idx = np.logical_and(
                (objects[0,:]>= x),
                (np.sqrt((objects[0,:]-x)**2+(objects[1,:]-y)**2) <= beam)
            )

            # above and below lines
            upper = np.tan(theta+angle/2)
            lower = np.tan(theta-angle/2)
            ind = np.arange(len(idx))
            for i in ind:
                if idx[i]:
                    dx = objects[0,i] - x
                    if y+upper*dx < objects[1,i] or y+lower*dx > objects[1,i]:
                        idx[i] = False

            return objects[:,idx]

        # intersection of line and circle
        def intersect(p1,p2,obj):
            x1 = p1[0] - obj[0]
            x2 = p2[0] - obj[0]
            y1 = p1[1] - obj[1]
            y2 = p2[1] - obj[1]

            r = obj[2]

            dx = x2-x1
            dy = y2-y1
            dr = np.sqrt(dx*dx + dy*dy)
            D = x1*y2 - x2*y1

            cross = False
            disc = r**2*dr**2 - D**2
            if disc>=0:
                cross = True
                xp = (D*dy + np.sign(dy)*dx*np.sqrt(r**2*dr**2 - D**2)) / dr**2
                xm = (D*dy - np.sign(dy)*dx*np.sqrt(r**2*dr**2 - D**2)) / dr**2
                yp = (-D*dx + np.abs(dy)*np.sqrt(r**2*dr**2 - D**2)) / dr**2
                ym = (-D*dx - np.abs(dy)*np.sqrt(r**2*dr**2 - D**2)) / dr**2
                
                dp = np.sqrt( (xp+obj[0])**2 + (yp+obj[1])**2 )
                dm = np.sqrt( (xm+obj[0])**2 + (ym+obj[1])**2 )
                if dp >= dm:
                    p2 = (xm+obj[0],ym+obj[1])
                else:
                    p2 = (xp+obj[0],yp+obj[1])

            return p2, cross
        
        if self.animate and round(self.time,1)%.1==0:
            ax.clear()
        x,z,_,theta,_,_ = state
        beam,angle,res = lidar
        
        rays = np.zeros((2,res))
        if beams:
            objects = seenObjects([x,z,theta],angle,beam,objects)
            
            angles = np.linspace(-angle/2,angle/2,num=res)
            for i,a in enumerate(angles):
                x1,y1 = x,z
                x2,y2 = x+beam*np.cos(theta+a),z+beam*np.sin(theta+a)
                
                # check for lidar intersection
                for obj in objects.T:
                    p,cross = intersect((x1,y1),(x2,y2),obj)
                    if cross:
                        if rays[0,i] == 0 or np.linalg.norm(rays[:,i]) > np.sqrt((p[0]-x1)**2+(p[1]-y1)**2):
                            x2,y2 = p
                            rays[0,i] = x2-x1
                            rays[1,i] = y2-y1

                if self.animate and round(self.time,1)%.1==0:
                    ax.plot([x1,x2],[y1,y2],'k-')

        else:
            if self.animate and round(self.time,1)%.1==0:
                ax.plot([x,x+beam*np.cos(theta+angle/2)],[z,z+beam*np.sin(theta+angle/2)],'k--')
                ax.plot([x,x+beam*np.cos(theta-angle/2)],[z,z+beam*np.sin(theta-angle/2)],'k--')
                a = np.linspace(-angle/2,angle/2,int(res/3))
                xs = x+beam*np.cos(theta+a)
                zs = z+beam*np.sin(theta+a)
                ax.plot(xs,zs,'k.',markersize=1)

                xs = objects[0,:]
                ys = objects[1,:]
                s = objects[2,:]
                ax.scatter(xs,ys,50*s,'r')

        if self.animate and round(self.time,1)%.1==0:
            ax.set_ylabel('Height (m)')
            ax.set_xlim([x-0.5*beam,x+2.5*beam])
            ax.set_ylim([z-0.75*beam,z+0.75*beam])
            ax.set_aspect('equal')

        return rays

    def update_grid(self, ax,lidar,rays,res=1):

        # returns the neighbors of a vertex v in G
        def neighbors(v,G):
            
            # initial neighbors
            i,j = v
            row = np.array([i-1,i-1,i-1,i,i,i+1,i+1,i+1])
            col = np.array([j-1,j,j+1,j-1,j+1,j-1,j,j+1])

            # remove cells out of range
            r,c = np.shape(G)
            low = np.logical_and(row>=0, col>=0)
            high = np.logical_and(row<=r, col<=c)
            idx = np.logical_and(low, high)
            row = np.delete(row,~idx)
            col = np.delete(col,~idx)

            return list(zip(row,col))
        
        beam,_,_ = lidar
        r,c = int(1.5*beam/res), int(3*beam/res)
        grid = np.zeros((r,c))
        x,y = int(c/6),int(r/2)
                    
        grid[y,x] = 1

        r,c = np.shape(rays)
        for i in range(c):
            if rays[0,i] != 0:
                grid[(y+rays[1,i]).astype(int),(x+rays[0,i]).astype(int)] = 1
        
        if self.animate and round(self.time,1)%.1==0:
            ax.clear()
            ax.imshow(grid,cmap='gray')
            ax.invert_yaxis()
            ax.set_aspect('equal')
            ax.set_yticklabels([])
            ax.set_xticklabels([])
            ax.set_xlabel('Distance (m)')
            ax.set_ylabel('Height (m)')

        grid[y,x] = 0
        padded = grid.copy()
        r,c = np.shape(grid)
        for i in range(r):
            for j in range(c):
                if grid[i,j]:
                    n = neighbors((i,j),grid)
                    for k in n:
                        padded[k] = 1
    
        return padded

    def step(self, action):

        
        err_msg = f"{action!r} ({type(action)}) invalid"
        assert self.state is not None, "Call reset before using step method."
        
        #Extra states
        x, z, v, theta, theta_dot, gamma = self.state
        rho = np.random.normal(self.rhoNom,0.0)
        
        #Control inputs
        if (self.time > 0):
            self.EKF((self.thrust_stale, self.delta_e_stale))
        thrust, stateCommand, delta_e = action

        error = (np.array([self.stateEstimate]).T-np.array([stateCommand]).T)
        controlFull = self.KFull @ error
        delta_e = delta_e-controlFull[0][0]

        x_dot, z_dot, v_dot, theta_dot, theta_ddot, gamma_dot = self.calculateStateDerivatives(self.state, (thrust, delta_e),rho)

        #Old controls for filter
        self.delta_e_stale = delta_e
        self.thrust_stale = thrust

        # integrate
        x += x_dot*self.dt
        z += z_dot*self.dt
        v += v_dot*self.dt 
        theta += theta_dot*self.dt
        theta_dot += theta_ddot*self.dt
        gamma += gamma_dot*self.dt

        state = np.array([x,z,v,theta,theta_dot,gamma])
        action = np.array([thrust,delta_e])

        self.state = (list(np.reshape(state,(6,))))
        self.time += self.dt
        terminated = bool(x < -self.x_thres
            or x > self.x_thres
            or z > self.z_thresHigh
            or z < self.z_thresLow
            or v < -self.v_thres
            or v > self.v_thres
            or theta < -self.theta_thres
            or theta > self.theta_thres
            or theta_dot < -self.theta_dot_thres
            or theta_dot > self.theta_dot_thres
            or gamma < -self.gamma_thres
            or gamma > self.gamma_thres)
        
        if not terminated:
            reward = 1.0
        elif self.steps_beyond_terminated is None:
            self.steps_beyond_terminated = 0
            reward = 0.0
            print(x < -self.x_thres
            ,z > self.z_thresHigh
            , z < self.z_thresLow
            ,v < -self.v_thres
            ,v > self.v_thres
            ,theta < -self.theta_thres
            ,theta > self.theta_thres
            ,theta_dot < -self.theta_dot_thres
            ,theta_dot > self.theta_dot_thres
            ,gamma < -self.gamma_thres
            ,gamma > self.gamma_thres)
        else:
            if self.steps_beyond_terminated == 0:
                gym.logger.warn(
                    "You are calling 'step()' even though this "
                    "environment has already returned terminated = True. You "
                    "should always call 'reset()' once you receive 'terminated = "
                    "True' -- any further steps are undefined behavior."
                )
            self.steps_beyond_terminated += 1
            reward = 0.0

        self.update_plot(self.axs[0],state,self.lidar,self.objects)
        rays = self.update_plot(self.axs[1],state,self.lidar,self.objects,beams=True)
        self.grid = self.update_grid(self.axs[2],self.lidar,rays)

        if self.animate and round(self.time,2)%.1==0:
            self.axs[0].set_title('Ground Truth')
            self.axs[1].set_title('Lidar View')
            self.axs[2].set_title('Occupancy Grid')
            plt.show()
            plt.pause(0.01)

        return state, reward, terminated, rays.astype(int)

    def reset(self,animate=True):
        self.state = np.array([0.0,100.0,self.vNom,0.0,0.0,0.0])
        self.state[2:] = self.coherentCommand(4.4,0/180*np.pi)
        self.stateEstimate = self.coherentCommand(4.4,0/180*np.pi)
        self.Pestimation = self.Qestimation.copy()
        self.steps_beyond_terminated = None
        self.time = 0
        self.calculateGains()

        self.animate = animate
        %matplotlib qt
        plt.close()
        self.fig,self.axs = plt.subplots(3,1,figsize=(6,10))

        num = 5
        x_pos = np.linspace(self.state[0]+40,self.state[0]+240,num)
        x_pos = np.hstack((x_pos,x_pos))
        y_pos = np.random.uniform(low=self.state[1]-8,high=self.state[1]-2,size=num)
        y_pos = np.hstack((y_pos,y_pos+8))

        sizes = np.random.uniform(low=1,high=1,size=num*2)
        self.objects = np.stack((x_pos,y_pos,sizes))

        return self.state

    def close(self):
        pass

[[0.00425524 0.72512213]]


In [28]:
env = Drone()
state = env.reset(animate=False)
stateRef = env.coherentCommand(4.4,0/180*np.pi)
stateRefFull = np.hstack(([0], [0],stateRef ))
print(stateRef)
elevRef = env.elevatorFromAlpha(stateRef[1] - stateRef[3])
controlCommand = (4 , elevRef)
rho = env.rhoNom
Acts, Bcts = env.calculateCTSABMatrix(stateRef, controlCommand)
A = env.calculateANumerical(stateRefFull, controlCommand, rho, step=10**-5)
print((A[2:,2:]-Acts)/np.linalg.norm(Acts))
print(A[2:,2:])
print(Acts)

[12.17630076914735, 0.14904511220222869, 0, 0.0]
[[-6.07835065e-11 -8.12644935e-08  0.00000000e+00 -8.12643868e-08]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.24075153e-03  1.38990186e-01 -4.04054445e-02 -1.38990029e-01]
 [ 8.29281629e-08 -5.05112611e-11  0.00000000e+00  2.61894186e-09]]
[[-2.23344742e-01 -5.68946996e+00  0.00000000e+00 -4.12077530e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 7.89323849e+00 -8.57293524e+02 -6.09734472e+01  8.57293760e+02]
 [ 1.29703880e-01  3.43988756e+00  0.00000000e+00 -3.43988368e+00]]
[[-2.23344651e-01 -5.68934733e+00  0.00000000e+00 -4.12065267e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.52671733e-02 -1.06703533e+03  0.00000000e+00  1.06703533e+03]
 [ 1.29578738e-01  3.43988764e+00  0.00000000e+00 -3.43988764e+00]]


In [5]:
np.set_printoptions(threshold=np.inf)
env = Drone()
state = env.reset(animate=False)
stateRef = env.coherentCommand(4,0/180*np.pi)
elevRef = env.elevatorFromAlpha(stateRef[1] - stateRef[3])
stateRef = np.hstack((0,0,stateRef))
print(stateRef)
control = (4, elevRef)
print(env.calculateStateDerivatives(state, control, env.rhoNom))

[ 0.          0.         11.93290061  0.15851512  0.          0.        ]
[[ 1.21763008e+01]
 [ 0.00000000e+00]
 [-1.23614165e-01]
 [ 0.00000000e+00]
 [ 1.00118846e+01]
 [-1.52441515e-03]]


In [50]:
np.set_printoptions(threshold=np.inf)
env = Drone()
state = env.reset(animate=False)
iterations = 2000
traj = np.zeros((7,iterations))
trajEst = np.zeros((5,iterations))
thrustCommand = np.zeros(iterations)+4.4+0.1
elvActual = np.zeros(iterations)

for iter in range(0, iterations):
    stateRef = env.coherentCommand(thrustCommand[iter],0/180*np.pi)
    elevRef = env.elevatorFromAlpha(stateRef[1] - stateRef[3])
    action = [thrustCommand[iter],stateRef , elevRef] 
    state, reward, done, grid = env.step(action)
    elvActual[iter] = env.delta_e_stale

    
    traj[:,iter] = np.hstack((state.flatten(),env.time))
    trajEst[:, iter] = np.hstack((env.stateEstimate,env.time))
    if done:
        break

r,c = np.shape(grid)
for i in range(r-1):
    for j in range(c-1):
        if grid[i,j]:
            plt.scatter(i,j)
plt.show()

In [66]:
import importlib
from rrtplanner import plot_rrt_lines, plot_path, plot_og, plot_start_goal
importlib.reload(ConvexMotionPlanning)
np.set_printoptions(threshold=np.inf)
env = Drone()
state = env.reset(animate=True)
iterations = 2000
rrtPlot = False
traj = np.zeros((7,iterations))
commandLen = 400
thrustCommandVal = 4.4+0.1
thrustCommand = np.zeros(iterations)+thrustCommandVal
stateCommand = env.coherentCommand(thrustCommand[0],0/180*np.pi)
elivCommandRef = env.elevatorFromAlpha(stateCommand[1]-stateCommand[3])
elivCommand = np.zeros(iterations) + elivCommandRef
xCommand = np.zeros(iterations)
yCommand = np.zeros(iterations)
elvActual = np.zeros(iterations)

refCommand = np.zeros((iterations, 4))
for i in range(len(thrustCommand)):
    refCommand[i,:] = np.array(stateCommand)
thrustCommandRef = thrustCommand[0]
controlRef = (thrustCommandVal, elivCommandRef)
print(thrustCommand.shape)

pathDist = 100
for iter in range(0, iterations):
    action = [thrustCommand[iter], refCommand[iter, :], elivCommand[iter]] 
    state, reward, done, grid = env.step(action)
    traj[:,iter] = np.hstack((state.flatten(),env.time))
    elvActual[iter] = env.delta_e_stale

    if(iter%pathDist == 0):
        midpoint =37
        lookAhead = 48
        orignX = 25
        xstart = np.array([midpoint, orignX]) 
        xgoal = np.array([midpoint, orignX+lookAhead])
        n = 3000
        r_rewire = 5
        rrts = RRTStar(env.grid[0:midpoint+1, 0:80], n, r_rewire, pbar = False) 
        T, gv = rrts.plan(xstart, xgoal)
        path = rrts.route2gv(T, gv)
        path_pts = rrts.vertices_as_ndarray(T, path)
        tEnd = commandLen
        if(rrtPlot):
            fig = plt.figure()
            ax = fig.add_subplot()

            #these functions alter ax in-place.
            plot_og(ax, env.grid)
            plot_start_goal(ax, xstart, xgoal)
            plot_rrt_lines(ax, T)
            plot_path(ax, path_pts)
        refStates = env.coherentCommand(thrustCommandVal,0/180*np.pi)
        referencePoints, referenceVels = ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)
        referencePointsDyn, referenceVelsDyn = ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)
        for i in range(len(referencePointsDyn)):
            referencePointsDyn[i][0] = referencePointsDyn[i][0]-refStates[0]*np.sin(refStates[3])*i*env.dt-midpoint
            referencePointsDyn[i][1] = referencePointsDyn[i][1]-refStates[0]*np.cos(refStates[3])*i*env.dt-orignX

        Acts, Bcts = env.calculateCTSABMatrix(refStates, controlRef)
        Aopt = np.eye(Acts.shape[0]+2)
        #A = Aopt + env.calculateANumerical(stateRefFull, controlRef, env.rhoNom, step=10**-5)*env.dt
        Aopt[0, 2] = env.dt
        Aopt[1, 5] = refStates[0]*env.dt
        Aopt[2:,2:] = Aopt[2:,2:]+Acts*env.dt
        Bopt = np.zeros([6,2])
        Bopt[2:,0:1] = Bcts*env.dt
        alphaEst = refStates[1] - refStates[3]
        Bopt[2, 1] = 1/env.m*np.cos(alphaEst)*env.dt
        Bopt[5, 1] = 1/env.m*np.sin(alphaEst)/refStates[0]*env.dt
        xstart = np.concatenate(([0.,0.], np.array(env.stateEstimate) - np.array(refStates)))
        xgoal = np.concatenate(([0.,100 - state[1]], [0.,0.,0.,0.]))
        print(xgoal)
        xsol, usol = ConvexMotionPlanning.localTrajOpt(Aopt, Bopt, tEnd, env.grid, referencePoints, referencePointsDyn, xstart, xgoal)
        for i in range(np.min((tEnd, iterations-iter))):
            thrustCommand[iter+i] = usol[i][1] + thrustCommandVal 
            elivCommand[iter + i] = usol[i][0] + elivCommandRef
            xCommand[iter+i] = xsol[i][0]+refStates[0]*np.cos(0)*i*env.dt+env.state[0]
            yCommand[iter+i] = xsol[i][1]+refStates[0]*np.sin(0)*i*env.dt+env.state[1]
            refCommand[iter+i, :] = xsol[i][2:6].T + np.array(refStates)

    if done:

        break

r,c = np.shape(grid)
for i in range(r-1):
    for j in range(c-1):
        if grid[i,j]:
            plt.scatter(i,j)
plt.show()

(2000,)
[0.0 array([0.]) 0.0 0.0 0.0 0.0]
     pcost       dcost       gap    pres   dres
 0:  2.0099e+03 -2.5801e+05  3e+05  2e-01  5e-06
 1:  2.6130e+03 -1.4146e+05  2e+05  6e-02  2e-06
 2:  3.0188e+03 -1.3939e+05  2e+05  6e-02  2e-06


KeyboardInterrupt: 

In [13]:
print(env.KFull)

[[ -0.46573365 -12.31021471   3.81806685  16.35481077]]


In [83]:
# Testing out perfect state knowledge

import importlib
from rrtplanner import plot_rrt_lines, plot_path, plot_og, plot_start_goal
importlib.reload(ConvexMotionPlanning)
np.set_printoptions(threshold=np.inf)
env = Drone()
state = env.reset(animate=True)
iterations = 1000
rrtPlot = False
traj = np.zeros((7,iterations))
commandLen = 450
thrustCommandVal = 4.4
thrustCommand = np.zeros(iterations)+thrustCommandVal
stateCommand = env.coherentCommand(thrustCommand[0],0/180*np.pi)
elivCommandRef = env.elevatorFromAlpha(stateCommand[1]-stateCommand[3])
elivCommand = np.zeros(iterations) + elivCommandRef
xCommand = np.zeros(iterations)
yCommand = np.zeros(iterations)
elvActual = np.zeros(iterations)

refCommand = np.zeros((iterations, 4))
for i in range(len(thrustCommand)):
    refCommand[i,:] = np.array(stateCommand)
thrustCommandRef = thrustCommand[0]
controlRef = (thrustCommandVal, elivCommandRef)
print(thrustCommand.shape)

pathDist = 25
for iter in range(0, iterations):
    action = [thrustCommand[iter], refCommand[iter, :], elivCommand[iter]] 
    state, reward, done, grid = env.step(action)
    traj[:,iter] = np.hstack((state.flatten(),env.time))
    elvActual[iter] = env.delta_e_stale

    if(iter%pathDist == 0):
        midpoint =37
        lookAhead = 54
        orignX = 25
        xstart = np.array([midpoint, orignX]) 
        xgoal = np.array([midpoint, orignX+lookAhead])
        n = 3000
        r_rewire = 5
        rrts = RRTStar(env.grid[0:midpoint+1, 0:80], n, r_rewire, pbar = False) 
        T, gv = rrts.plan(xstart, xgoal)
        path = rrts.route2gv(T, gv)
        path_pts = rrts.vertices_as_ndarray(T, path)
        tEnd = commandLen
        if(rrtPlot):
            fig = plt.figure()
            ax = fig.add_subplot()

            #these functions alter ax in-place.
            plot_og(ax, env.grid)
            plot_start_goal(ax, xstart, xgoal)
            plot_rrt_lines(ax, T)
            plot_path(ax, path_pts)
        refStates = env.coherentCommand(thrustCommandVal,0/180*np.pi)
        referencePoints, referenceVels = ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)
        referencePointsDyn, referenceVelsDyn = ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)
        for i in range(len(referencePointsDyn)):
            referencePointsDyn[i][0] = referencePointsDyn[i][0]-refStates[0]*np.sin(refStates[3])*i*env.dt-midpoint
            referencePointsDyn[i][1] = referencePointsDyn[i][1]-refStates[0]*np.cos(refStates[3])*i*env.dt-orignX

        Acts, Bcts = env.calculateCTSABMatrix(refStates, controlRef)

        D, V = sci.linalg.eig(Acts)
        eigMatrix = np.zeros((4,4), dtype=complex)
        eigMatrix[0,0] = D[0]
        eigMatrix[1,1] = D[1]
        eigMatrix[2,2] = D[2]
        eigMatrix[3,3] = D[3]
        Adropout = np.real(V @ eigMatrix @ np.linalg.inv(V))

        Aopt = np.eye(Acts.shape[0]+2)
        #A = Aopt + env.calculateANumerical(stateRefFull, controlRef, env.rhoNom, step=10**-5)*env.dt
        Aopt[0, 2] = env.dt
        Aopt[1, 5] = refStates[0]*env.dt
        Aopt[2:,2:] = Aopt[2:,2:]+Adropout*env.dt
        Bopt = np.zeros([6,2])
        Bopt[2:,0:1] = Bcts*env.dt
        alphaEst = refStates[1] - refStates[3]
        Bopt[2, 1] = 1/env.m*np.cos(alphaEst)*env.dt
        Bopt[5, 1] = 1/env.m*np.sin(alphaEst)/refStates[0]*env.dt
        #xstart = np.concatenate(([0.,0.], np.array(env.stateEstimate) - np.array(refStates)))
        xstart = np.concatenate(([0.,0.], state[2:].flatten()- np.array(refStates)))
        #Adding this term to get rid of wobbles in the fast pitch pole reference
        xstart[3] = 0

        xgoal = np.concatenate(([0.,100 - state[1]], [0.,0.,0.,0.]))
        print(xgoal)
        xsol, usol = ConvexMotionPlanning.localTrajOpt(Aopt, Bopt, tEnd, env.grid, referencePoints, referencePointsDyn, xstart, xgoal)
        for i in range(np.min((tEnd, iterations-iter))):
            thrustCommand[iter+i] = usol[i][1] + thrustCommandVal 
            elivCommand[iter + i] = usol[i][0] + elivCommandRef
            xCommand[iter+i] = xsol[i][0]+refStates[0]*np.cos(0)*i*env.dt+env.state[0]
            yCommand[iter+i] = xsol[i][1]+refStates[0]*np.sin(0)*i*env.dt+env.state[1]
            refCommand[iter+i, :] = xsol[i][2:6].T + np.array(refStates)

    if done:

        break

r,c = np.shape(grid)
for i in range(r-1):
    for j in range(c-1):
        if grid[i,j]:
            plt.scatter(i,j)
plt.show()

(1000,)
[0.0 array([0.]) 0.0 0.0 0.0 0.0]
     pcost       dcost       gap    pres   dres
 0:  2.4963e+02 -1.8694e+05  2e+05  4e-12  5e-06
 1:  8.7127e+01 -8.5769e+03  9e+03  4e-12  2e-07
 2:  8.3788e+01 -3.0563e+03  3e+03  1e-12  3e-12
 3:  6.6702e+01 -2.0286e+02  3e+02  3e-13  2e-12
 4:  6.6562e+01  4.7121e+01  2e+01  2e-13  2e-12
 5:  6.6512e+01  6.6314e+01  2e-01  5e-15  2e-12
 6:  6.6511e+01  6.6509e+01  2e-03  8e-16  2e-12
 7:  6.6511e+01  6.6511e+01  2e-05  9e-16  2e-12
Optimal solution found.
[0.0 array([-0.00070825]) 0.0 0.0 0.0 0.0]
     pcost       dcost       gap    pres   dres
 0:  4.7923e+02 -2.6596e+05  3e+05  7e-02  5e-06
 1:  4.5768e+02 -5.4133e+04  6e+04  1e-02  9e-07
 2:  6.2435e+02 -5.1077e+04  5e+04  1e-02  7e-07
 3:  6.1482e+02 -9.3570e+03  1e+04  2e-03  1e-07
 4:  6.4174e+02 -4.7600e+03  5e+03  7e-04  5e-08
 5:  6.4877e+02  5.7595e+02  7e+01  8e-06  5e-10
 6:  6.4880e+02  6.4807e+02  7e-01  8e-08  7e-12
 7:  6.4880e+02  6.4879e+02  7e-03  8e-10  5e-12
 8:  6.4880

In [82]:
path = rrts.route2gv(T, gv)
path_pts = rrts.vertices_as_ndarray(T, path)
fig = plt.figure()
ax = fig.add_subplot()

#these functions alter ax in-place.
plot_og(ax, env.grid)
plot_start_goal(ax, xstart, xgoal)
plot_rrt_lines(ax, T)
plot_path(ax, path_pts)

In [84]:
def state_plots(traj, elvActual):

    def plot_state(ax,x,y,xlabel,ylabel):
        lim = 2
        ax.plot(x,y)
        ax.set_ylim([min(y)-lim,max(y)+lim])
        ax.set_ylabel(ylabel)
        ax.set_xlabel(xlabel)

        return
    x = traj[0,:]
    z = traj[1,:]
    v = traj[2,:]
    theta = traj[3,:]
    thetaDot = traj[4,:]
    gamma = traj[5,:]
    time = traj[6,:]

    plt.close()
    fig, axs = plt.subplots(3,2, figsize=(8,8))
    plot_state(axs[0, 0],x,z,"Downrange distance (m)","Height (m)")
    axs[0,0].scatter(env.objects[0,:],env.objects[1,:], color = "red" )
    plot_state(axs[0, 1],time,(theta-gamma)*180/np.pi,"Time (s)","alpha (deg)")
    plot_state(axs[1, 0],time,gamma*180/np.pi,"Time (s)","Gamma (deg)")
    plot_state(axs[1, 1],time,v,"Time (s)","Velocity (m/s)")
    plot_state(axs[2, 0],time,theta*180/np.pi,"Time (s)","Theta (deg)")
    plot_state(axs[2, 1],time,elvActual,"Time (s)","Elevator actual (deg)")

    fig.show()
    return

state_plots(traj, elvActual)

In [85]:
def state_plots(traj,control,xCommand, yCommand, elivCommand,elvActual, refCommand):

    def plot_state(ax,x,y,xlabel,ylabel):
        lim = 2
        ax.plot(x,y)
        ax.set_ylim([min(y)-lim,max(y)+lim])
        ax.set_ylabel(ylabel)
        ax.set_xlabel(xlabel)

        return
    vRef = refCommand[:,0]
    thetaRef = refCommand[:,1]
    gammaRef = refCommand[:,3]

    x = traj[0,:]
    z = traj[1,:]
    v = traj[2,:]
    theta = traj[3,:]
    thetaDot = traj[4,:]
    gamma = traj[5,:]
    time = traj[6,:]

    plt.close()
    fig, axs = plt.subplots(3,3, figsize=(8,8))
    plot_state(axs[0, 0],x,z,"Downrange distance (m)","Height (m)")
    plot_state(axs[0, 0],xCommand,yCommand,"Downrange distance (m)","Height (m)")
    axs[0,0].scatter(env.objects[0,:],env.objects[1,:], color = "red" )
    axs[0,0].set_ylim((90,110))
    plot_state(axs[0, 1],time,(theta-gamma)*180/np.pi,"Time (s)","alpha (deg)")
    plot_state(axs[0, 1],time,(thetaRef-gammaRef)*180/np.pi,"Time (s)","alpha (deg)")
    plot_state(axs[0, 2],time,elvActual,"Time (s)","Elevator Actual")
    plot_state(axs[0, 2],time,elivCommand,"Time (s)","Elevator Command")
    plot_state(axs[1, 0],time,gamma*180/np.pi,"Time (s)","Gamma (deg)")
    plot_state(axs[1, 0],time,gammaRef*180/np.pi,"Time (s)","Gamma (deg)")
    plot_state(axs[1, 1],time,v,"Time (s)","Velocity (m/s)")
    plot_state(axs[1, 1],time,vRef,"Time (s)","Velocity (m/s)")
    plot_state(axs[2, 0],time,theta*180/np.pi,"Time (s)","Theta (deg)")
    plot_state(axs[2, 0],time,thetaRef*180/np.pi,"Time (s)","Theta (deg)")
    plot_state(axs[2, 1],time,control,"Time (s)","Thrust Command (N)")
    fig.show()
    return

state_plots(traj,thrustCommand, xCommand, yCommand, elivCommand, elvActual, refCommand)

In [39]:
def est_plots(traj, trajEst,control):

    def plot_state(ax,x,y,xlabel,ylabel):
        lim = 2
        ax.plot(x,y)
        ax.set_ylim([min(y)-lim,max(y)+lim])
        ax.set_ylabel(ylabel)
        ax.set_xlabel(xlabel)
        return
    def plot_state_dashed(ax,x,y,xlabel,ylabel):
        lim = 2
        ax.plot(x,y,'--')
        ax.set_ylim([min(y)-lim,max(y)+lim])
        ax.set_ylabel(ylabel)
        ax.set_xlabel(xlabel)

        return
    
    x = traj[0,:]
    z = traj[1,:]
    v = traj[2,:]
    vEst =  trajEst[0,:]
    theta = traj[3,:]
    thetaEst = trajEst[1,:]
    thetaDot = traj[4,:]
    thetaDotEst = trajEst[2,:]
    gamma = traj[5,:]
    gammaEst = trajEst[3,:]
    time = traj[6,:]

    plt.close()
    fig, axs = plt.subplots(4,2, figsize=(8,1))
    plot_state(axs[0, 0],time,theta*180/np.pi,"Time (s)", "Theta (deg)")
    plot_state(axs[0, 1],time,thetaEst*180/np.pi,"Time (s)", "Theta Estimate (deg)")
    plot_state(axs[1, 0],time,thetaDot*180/np.pi,"Time (s)", "ThetaDot (deg/s)")
    plot_state(axs[1, 1],time,thetaDotEst*180/np.pi,"Time (s)", "ThetaDot Estimate (deg/s)")
    plot_state(axs[2, 0],time,v,"Time (s)", "Velocity (m/s)")
    plot_state(axs[2, 1],time,vEst,"Time (s)", "Velocity Estimate (m/s)")
    plot_state(axs[3, 0],time,gamma*180/np.pi,"Time (s)", "Gamma (deg)")
    plot_state(axs[3, 1],time,gammaEst*180/np.pi,"Time (s)", "Gamma Estimate (deg)")
    fig.show()
    return

est_plots(traj, trajEst, thrustCommand)

In [1]:
# Testing out ray tracing on the env.grid

#Basic sim setup
import importlib
from rrtplanner import plot_rrt_lines, plot_path, plot_og, plot_start_goal
importlib.reload(ConvexMotionPlanning)
np.set_printoptions(threshold=np.inf)
env = Drone()
state = env.reset(animate=True)
stateCommand = env.coherentCommand(4,0/180*np.pi)
elivCommandRef = env.elevatorFromAlpha(stateCommand[1]-stateCommand[3])

action = [4, stateCommand, elivCommandRef] 
controlRef = (4, elivCommandRef)
state, reward, done, grid = env.step(action)
commandLen = 400

#Path planning
midpoint =37
lookAhead = 48
orignX = 25
xstart = np.array([midpoint, orignX]) 
xgoal = np.array([midpoint, orignX+lookAhead])
n = 3000
r_rewire = 5
rrts = RRTStar(env.grid[0:midpoint, 0:80], n, r_rewire, pbar = False) 
T, gv = rrts.plan(xstart, xgoal)
path = rrts.route2gv(T, gv)
path_pts = rrts.vertices_as_ndarray(T, path)
tEnd = commandLen

referencePoints, referenceVels= ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)

#Plot RRT
fig = plt.figure()
ax = fig.add_subplot()
print(env.grid.shape)
plot_og(ax, env.grid)
plot_start_goal(ax, xstart, xgoal)
plot_rrt_lines(ax, T)
plot_path(ax, path_pts)
ax.set_ylabel("Downrange distance in occupancy grid (m)")
ax.set_xlabel("Vertical distance in occupancy grid (m)")

#Generate search plot
numDirections = 8
directs = ConvexMotionPlanning.generateDirections(numDirections)

fig, ax = plt.subplots()
xRefsToPlot = list(zip(*referencePoints))[0]
yRefsToPlot = list(zip(*referencePoints))[1]

indexes = range(len(xRefsToPlot))
#indexes = indexes[0::75]
for i in indexes:
    cords = ConvexMotionPlanning.searchFromCord([xRefsToPlot[i],yRefsToPlot[i]], directs, env.grid)
    if (((np.sum(np.square((cords-np.array([xRefsToPlot[i],yRefsToPlot[i]]))), axis =1)) < 8**2).any()):
        plt.scatter(cords[:, 0], cords[:, 1], color = plt.cm.winter(i/np.max(indexes)))
        plt.scatter(xRefsToPlot[i], yRefsToPlot[i], color = "red")

    #plt.scatter(xRefsToPlot[i],yRefsToPlot[i], color = plt.cm.autumn(i/np.max(indexes)))
    #plt.axis('equal')
ax.imshow(env.grid[:, 0:80].T)
ax.invert_yaxis()
plt.plot(xRefsToPlot,yRefsToPlot, color = 'blue')
ax.set_ylabel("Downrange distance in occupancy grid (m)")
ax.set_xlabel("Vertical distance in occupancy grid (m)")
#ax.set(xlim=(0, 46), ylim = (14,60))


#In place plot
refStates = env.coherentCommand(4,0/180*np.pi)
referencePointsDyn, referenceVelsDyn = ConvexMotionPlanning.calculateReferencePoints(tEnd+1, path_pts)
for i in range(len(referencePointsDyn)):
    referencePointsDyn[i][0] = referencePointsDyn[i][0]-refStates[0]*np.sin(refStates[3])*i*env.dt-midpoint
    referencePointsDyn[i][1] = referencePointsDyn[i][1]-refStates[0]*np.cos(refStates[3])*i*env.dt-orignX

fig2, ax2 = plt.subplots()
xRefsToPlotDyn = list(zip(*referencePointsDyn))[0]
yRefsToPlotDyn = list(zip(*referencePointsDyn))[1]

indexes = range(len(xRefsToPlot))
#indexes = indexes[0::75]
for i in indexes:
    cords = ConvexMotionPlanning.searchFromCord([xRefsToPlot[i],yRefsToPlot[i]], directs, env.grid)
    if (((np.sum(np.square((cords-np.array([xRefsToPlot[i],yRefsToPlot[i]]))), axis =1)) < 8**2).any()):
        plt.scatter(cords[:, 1]-yRefsToPlot[i]+yRefsToPlotDyn[i], cords[:, 0]- xRefsToPlot[i]+xRefsToPlotDyn[i], color = plt.cm.winter(i/np.max(indexes)))
    #plt.scatter(xRefsToPlot[i],yRefsToPlot[i], color = plt.cm.autumn(i/np.max(indexes)))
        plt.axis('equal')

plt.plot(yRefsToPlotDyn,xRefsToPlotDyn, color = 'blue')
ax2.set_ylabel("Vertical distance, linearized frame (m)")
ax2.set_xlabel("Down range distance, linearized frame (m)")
#ax2.set(xlim=(-1, 40), ylim = (-1,100))
plt.show()



Acts, Bcts = env.calculateCTSABMatrix(refStates, controlRef)
Aopt = np.eye(Acts.shape[0]+2)
Aopt[0, 2] = env.dt
Aopt[1, 5] = refStates[0]*env.dt
Aopt[2:,2:] = Aopt[2:,2:]+Acts*env.dt
Bopt = np.zeros([6,2])
Bopt[2:,0:1] = Bcts*env.dt
alphaEst = refStates[1] - refStates[3]
Bopt[2, 1] = 1/env.m*np.cos(alphaEst)*env.dt
Bopt[5, 1] = 1/env.m*np.sin(alphaEst)/refStates[0]*env.dt
xstart = np.concatenate(([0.,0.], np.array(env.stateEstimate) - np.array(refStates)))
xgoal = np.concatenate(([0.,0.], [0.,0.,0.,0.]))
xsol, usol = ConvexMotionPlanning.localTrajOpt(Aopt, Bopt, tEnd, env.grid, referencePoints, referencePointsDyn, xstart, xgoal)
thrustCommand = np.zeros(tEnd)
xCommand = np.zeros(tEnd)
yCommand = np.zeros(tEnd)
refCommand = np.zeros((tEnd, 4))
for i in range(tEnd):
    thrustCommand[i] = usol[i][1] + env.thrust_stale 
    xCommand[i] = xsol[i][0]+refStates[0]*np.cos(0)*i*env.dt+env.state[0]+orignX
    yCommand[i] = xsol[i][1]+refStates[0]*np.sin(0)*i*env.dt+env.state[1]+midpoint
    refCommand[i, :] = xsol[i][2:6].T + np.array(refStates)

ax.plot(yCommand-100,xCommand, color = 'black')


NameError: name 'ConvexMotionPlanning' is not defined

In [60]:
Acts, Bcts = env.calculateCTSABMatrix(refStates, controlRef)
D, V = sci.linalg.eig(Acts)
eigMatrix = np.zeros((4,4), dtype=complex)
eigMatrix[0,0] = D[0]
eigMatrix[1,1] = D[1]
eigMatrix[2,2] = np.real(D[2])
eigMatrix[3,3] = np.real(D[3])
Adropout = np.real(V @ eigMatrix @ np.linalg.inv(V))
print(Adropout)

[[-2.19519439e-01  1.34213155e-02 -3.06432193e-02 -9.83013614e+00]
 [ 1.29907064e-01 -3.98068396e-03 -6.71147364e-04  7.85114218e-03]
 [-2.79967066e-02  1.72699202e-03 -3.98068396e-03 -1.27611529e+00]
 [ 1.29757955e-01 -3.97629356e-03 -6.69528868e-04  8.10414504e-03]]


In [85]:
plt.plot(thrustCommand[:])
plt.show() 